name: Main commit jobs

on:
    push:
        branches: ["main"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    create-zip:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Saves commit and pushes commit
              run: |
                echo "<?php define( 'TRANSGRESSION_COMMIT', '$(git rev-parse --short "$GITHUB_SHA")' );" > commit.php
                git config --global user.name '${{ env.CI_COMMIT_AUTHOR }}'
                git config --global user.email 'username@users.noreply.github.com'
                git commit -am "Version bump"
                git push
            - uses: actions/upload-artifact@v1
              with:
                  name: transgression
                  path: ${{ github.workspace }}/src
