name: Main commit jobs

on:
    push:
        branches: ["main"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    save-commit-theme:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
          - uses: actions/checkout@v3
          - name: Saves commit to file
            run: |
              echo "<?php define( 'TRANSGRESSION_COMMIT', '$(git rev-parse --short "$GITHUB_SHA")' );" > commit.php
          - name: Commits new file
            uses: stefanzweifel/git-auto-commit-action@v4
            with:
              commit_message: Version bump
          - name: Save theme
            uses: actions/upload-artifact@v1
            with:
                name: transgression
                path: ${{ github.workspace }}/src
